---
- name: Playbook to test creating IdM users from csv
  hosts: local
  pre_tasks:
    - name: PreTask Place holder
      ansible.builtin.debug:
        msg: "Add pre tasks here to run before roles"
  roles:
    - {role: create_idm_users}
